cache:
  directories:
    - $HOME/.m2

language: java

services:
  - docker

install: skip

stages:
  - test
  - package
  - deploy

jobs:
  include:
    - stage: test
      name: 'Testing application'
      script:
        - make test

    - stage: package
      name: 'Packaging application'
      script:
        - make package
        - make deploy/contract
    - stage: deploy
      name: 'Deploy application on heroku'
      script:
        - make deploy
